<?php

/*
| Actualités & Événements (source : https://rejeppat.org, articles WordPress).
| Les contenus injectés (spam) présents sur l'ancien site ont été retirés.
*/

return [
    [
        'slug' => 'formation-15-nouveaux-coachs',
        'title' => 'Le REJEPPAT forme 15 nouveaux coachs dans le cadre du renforcement des capacités',
        'date' => '2026-10-04',
        'categories' => [
            'evenements',
        ],
        'image' => 'formation-15-nouveaux-coachs',
        'content' => [
            'Date : Du 06 au 11 octobre 2026',
            'Organisateur : Réseau des Jeunes Producteurs et Professionnels Agricoles du Togo (REJEPPAT)',
            'Dans le cadre de ses actions de renforcement des capacités et de promotion de l’accompagnement des acteurs du monde agricole, le Réseau des Jeunes Producteurs et Professionnels Agricoles du Togo (REJEPPAT) organise une formation à l’endroit de 15 nouveaux coachs.',
            'Cette initiative vise à renforcer les compétences des participants afin de leur permettre d’assurer efficacement l’accompagnement, le suivi et l’encadrement des bénéficiaires des programmes et projets agricoles.',
            'La formation se déroulera du 06 au 11 octobre 2026 et constitue une étape importante dans le développement des compétences et la professionnalisation de l’accompagnement agricole au Togo.',
            'Lieu : Kara.',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua',
        'title' => 'Entrepreneuriat forestier : le REJEPPAT renforce les capacités de 22 maîtres formateurs à Sotouboua',
        'date' => '2026-10-03',
        'categories' => [
            'actualites',
            'evenements',
        ],
        'image' => 'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua',
        'content' => [
            'Après la validation des outils de formation en entrepreneuriat forestier le 1er septembre 2026, les acteurs du projet se sont réunis à Sotouboua, dans le centre du Togo, pour une session de renforcement des capacités des maîtres formateurs. Elle portait sur l’utilisation de ces outils et sur les techniques d’installation des champs école paysans (CEP).',
            'L’activité s’est déroulée en deux phases complémentaires. La phase théorique s’est tenu les 28 et 29 septembre 2026 à l’hôtel MON CLAIR. Elle a permis aux maîtres formateurs, acteurs clés du dispositif, de s’approprier les différents outils. Leurs observations et suggestions permettront à l’Institut National de Formation Agricole (INFA) d’affiner davantage les supports.',
            'La phase pratique s’est déroulée du 30 septembre au 2 octobre 2026 à la ferme « Ma Joie », à Kpété-Kpété, où les participants ont pu mettre en application les acquis théoriques.',
            'Cette activité visait à renforcer les compétences des maîtres formateurs en entrepreneuriat forestier et à partager les concepts, approches et outils contenus dans les manuels, afin de garantir une mise en œuvre harmonieuse sur le terrain.',
            'Durant les cinq jours, les participants se sont approprié : (i) le manuel sur les bonnes pratiques de gestion durable des forêts et des paysages, (ii) le manuel sur la création et la gestion d’une entreprise forestière intègre au Togo, (iii) la fiche technique des principales opportunités d’entrepreneuriat forestier au Togo, (iv) le manuel sur les outils d’accompagnement des maîtres formateurs et (v) le manuel sur la création et la gestion d’une pépinière arboricole.',
            'La session a reposé sur la méthode de formation par les pairs. Elle a alterné présentations, échanges, brainstorming, partages d’expériences et débats en groupe, complétés par des restitutions de cas pratiques en plénière et des jeux de rôle.',
            'Les séances pratiques d’installation de CEP ont permis aux vingt-deux maîtres formateurs d’acquérir les compétences nécessaires pour former à leur tour les 80 points focaux.',
            'Cette activité est mise en œuvre dans le cadre du projet « Renforcer les capacités institutionnelles pour former la prochaine génération de producteurs et de praticiens forestiers et agricoles » (GCP/GLO/1243/GER), mis en œuvre par la FAO avec le soutien financier du ministère fédéral allemand de l’Agriculture, de l’Alimentation et de l’Identité régionale (BMLEH)',
        ],
        'tags' => [
            'FAO',
            'CEP',
            'CTOPTOGO',
            'Environnement',
            'Agroécologie',
            'Togo',
            'JeunesAgriculteurs',
            'Forêt',
            'AHA',
            'AndreasHermesAkademie',
        ],
        'gallery' => [
            'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua-1',
            'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua-2',
            'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua-3',
            'entrepreneuriat-forestier-22-maitres-formateurs-sotouboua-4',
        ],
    ],
    [
        'slug' => 'education-forestiere-mission-suivi-ugp-rome',
        'title' => 'Projet Éducation forestière : le REJEPPAT reçoit une mission de suivi de l’UGP de Rome',
        'date' => '2026-10-01',
        'categories' => [
            'actualites',
        ],
        'image' => 'education-forestiere-mission-suivi-ugp-rome',
        'content' => [
            'Du 24 au 28 août 2026, une équipe du siège de la FAO en charge du projet Éducation forestière a conduit une mission de suivi auprès des partenaires de mise en œuvre du projet au Togo.',
            'L’équipe de mission, composée de M. Jose DIAZ DIAZ, chef de projet, et de Mlle Laureana De Prado, consultante, a bénéficié de l’appui de l’équipe de la FAO Togo, représentée notamment par Mme Ruth Atchoglo, facilitatrice FFF, ainsi que par ALIPOE Komla Prince.',
            'Le 25 août 2026, la délégation a été accueillie dans les locaux du REJEPPAT. Cette rencontre a permis aux deux parties de dresser un bilan des activités menées dans le cadre de la Lettre d’accord (LoA) du REJEPPAT, en mettant en exergue les progrès accomplis et les résultats obtenus. Les échanges ont également porté sur les contraintes rencontrées, l’équipe de mission ayant formulé à cette occasion des orientations pour guider les actions à venir.',
            'Compte tenu des délais inhérents au processus d’approbation des rapports, les deux parties ont convenu d’un commun accord de procéder à une transmission progressive des rapports et livrables, au fur et à mesure de l’achèvement de chaque activité.',
            'Dans le cadre de cette mission, des visites de terrain ont été réalisées dans les fermes Ma Joie, dans la région Centrale, ainsi que Cadette et Terre Bénie, dans la région des Plateaux, afin d’évaluer le dispositif de formation mis en place par le REJEPPAT.',
            'La mission s’est conclue par une réunion de clôture organisée à l’INFA de Tové, offrant aux partenaires et à l’équipe de mission l’occasion de dresser un bilan d’étape et d’échanger sur les collaborations nécessaires à la poursuite du projet.',
        ],
        'tags' => [
            'FAO',
            'CEP',
            'CTOPTOGO',
            'Environnement',
            'Agroécologie',
            'Togo',
            'JeunesAgriculteurs',
            'Forêt',
            'AHA',
            'AndreasHermesAkademie',
        ],
        'gallery' => [
            'education-forestiere-mission-suivi-ugp-rome-1',
            'education-forestiere-mission-suivi-ugp-rome-2',
            'education-forestiere-mission-suivi-ugp-rome-3',
            'education-forestiere-mission-suivi-ugp-rome-4',
        ],
    ],
    [
        'slug' => 'andreas-hermes-akademie-renforce-rejeppat-renafat-montage-projet',
        'title' => 'L’Andreas Hermes Akademie renforce les capacités du REJEPPAT et du ReNaFAT en montage de projet',
        'date' => '2026-09-21',
        'categories' => [
            'actualites',
        ],
        'image' => 'andreas-hermes-akademie-renforce-rejeppat-renafat-montage-projet',
        'content' => [
            'Depuis 2022, le Réseau des Jeunes Professionnels et Promoteurs Agricoles du Togo (REJEPPAT) et le Réseau National des Femmes Agricultrices du Togo (ReNaFAT) sont engagés dans un partenariat avec l’Andreas Hermes Akademie (AHA) dans le cadre du projet « Renforcement des organisations paysannes agricoles pour un développement agraire durable ».',
            'Cette coopération a permis à l’AHA d’accompagner les deux organisations dans leur développement organisationnel, contribuant ainsi à leur structuration interne, à leur repositionnement en tant qu’acteurs clés du secteur agricole togolais, et au renforcement de leur visibilité.',
            'C’est dans la continuité de cet accompagnement que dix-huit (18) participants — représentants des équipes techniques et membres des Bureaux Exécutifs des deux organisations — se sont réunis le 18 septembre 2026 à Lomé, au centre Wycliffe, pour une session de renforcement de capacités dédiée au montage de projet.',
            'Pendant une journée, la consultante de l’AHA, Mme Fatma Ben Rejeb, a guidé les participants à travers les différentes étapes clés de l’élaboration d’un projet : (i) Le passage du besoin identifié à l’idée de projet, (ii) la formulation de l’objectif, des résultats attendus et des activités, (iii) l’analyse des opportunités de financement, (iv) L’élaboration d’une proposition de projet et (v) la construction du budget et les stratégies de mobilisation de ressources',
            'La formation s’est clôturée par une séance de restitution en plénière devant un jury, permettant aux participants de s’exercer concrètement aux techniques de présentation de projet.',
            'Cette activité s’inscrit dans la continuité des actions menées grâce au partenariat entre l’AHA, le REJEPPAT et le ReNaFAT, avec le soutien financier du ministère fédéral allemand de la Coopération économique et du Développement (BMZ)',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'nouveaux-outils-formation-entrepreneuriat-forestier',
        'title' => 'Le REJEPPAT se dote de nouveaux outils de formation pour renforcer l’entrepreneuriat forestier',
        'date' => '2026-09-21',
        'categories' => [
            'actualites',
        ],
        'image' => 'nouveaux-outils-formation-entrepreneuriat-forestier',
        'content' => [
            'Le 1er septembre 2026, la salle de réunion de l’hôtel Flamboyant, à Atakpamé, a accueilli l’atelier de validation officielle du manuel de formation en entrepreneuriat forestier.',
            'Cette rencontre s’inscrit dans le cadre de la mise en œuvre du projet « Renforcer les capacités institutionnelles pour former la prochaine génération de producteurs et de praticiens forestiers et agricoles » (GCP/GLO/1243/GER).',
            'Ce projet vise à renforcer les capacités des organisations de producteurs forestiers et agricoles (OPFA) afin qu’elles puissent offrir de meilleurs services de formation et de développement des compétences aux praticiens de terrain – forestiers, exploitants forestiers agricoles, entreprises forestières communautaires et entrepreneurs – sur des thématiques liées à la gestion durable des forêts, avec une attention particulière portée aux jeunes femmes et hommes ruraux. Il bénéficie aux OPFA nationales du Guatemala, du Togo et du Vietnam.',
            'Au Togo, le projet associe le Réseau des jeunes producteurs et professionnels agricoles du Togo (REJEPPAT) et l’Institut national de formation agricole (INFA), qui accompagne le REJEPPAT dans le pilotage et l’expérimentation d’approches de formation destinées à renforcer les connaissances et les compétences des jeunes producteurs forestiers et agricoles sur divers sujets, notamment la production forestière et agricole durable, l’agroécologie et l’entrepreneuriat.',
            'Pour répondre à ces enjeux, l’INFA de Tové a conduit un diagnostic de terrain qui a abouti à l’élaboration d’un projet de manuel de formation en entrepreneuriat forestier.',
            'Cet atelier de validation poursuivait quatre objectifs : (i) présenter le contenu du manuel aux parties prenantes impliquées dans la préservation de l’environnement, (ii) analyser la pertinence et la cohérence du contenu du manuel et des outils qui l’accompagnent, (iii) formuler des amendements de fond et de forme sur le document, (iv) procéder à la validation du manuel.',
            'Réunis au nombre de vingt-trois (23), les participants ont examiné en détail cinq documents : (i) le manuel sur les bonnes pratiques de gestion durable des forêts et des paysages, (ii) le manuel sur la création et la gestion d’une entreprise forestière intègre au Togo, (iii) la fiche technique des principales opportunités d’entrepreneuriat forestier au Togo, (iv) le manuel sur les outils d’accompagnement des maîtres formateurs, et le (v) le manuel sur la création et la gestion d’une pépinière arboricole.',
            'À l’issue de ces travaux, les participants ont formulé des propositions de fond et de forme ainsi que des recommandations visant à adapter le manuel aux profils des bénéficiaires, avant de valider l’ensemble des documents.',
            'Ces outils validés serviront de base aux prochaines activités de formation des maîtres formateurs et à l’accompagnement des jeunes producteurs et productrices dans le développement d’activités forestières et agroforestières. Ceci se connecte avec l’objectif du projet',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'jeunes-mobilisent-agroecologie',
        'title' => 'Les jeunes se mobilisent pour l’agroécologie',
        'date' => '2026-08-26',
        'categories' => [
            'actualites',
        ],
        'image' => 'jeunes-mobilisent-agroecologie',
        'content' => [
            'Les matières premières nécessaires à la production du compost, du Bokashi et de l’Apichi (résidus de récolte, fientes/déjections animales, son de riz ou de maïs, cendres, eau, mélasse et levure pour le Bokashi, plantes à effet biopesticide pour l’Apichi) sont globalement disponibles à proximité de l’unité. Le promoteur KATIK Aboubakar assure lui-même la collecte et l’approvisionnement, sans difficulté majeure signalée',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'rejeppat-maritime-redynamise-gouvernance',
        'title' => 'Le REJEPPAT-Maritime redynamise sa gouvernance et ses orientations',
        'date' => '2025-06-05',
        'categories' => [
            'actualites',
        ],
        'image' => 'rejeppat-maritime-redynamise-gouvernance',
        'content' => [
            'Le REJEPPAT poursuit son engagement en faveur d’une agriculture durable à travers ses fermes écoles agroécologiques implantées dans plusieurs localités de la région centrale du Togo.',
            'Depuis plusieurs années, ces centres de formation permettent aux jeunes producteurs agricoles d’acquérir des compétences pratiques en agroécologie, gestion durable des sols, compostage biologique et entrepreneuriat agricole.',
            'L’objectif du programme est de favoriser l’insertion professionnelle des jeunes tout en promouvant des pratiques agricoles respectueuses de l’environnement et adaptées aux changements climatiques.',
            'Grâce à l’appui de plusieurs partenaires techniques et financiers, plus de 285 jeunes ont déjà été formés et plusieurs exploitations agricoles durables ont vu le jour dans différentes régions du pays.',
            'Le REJEPPAT ambitionne désormais d’étendre ce modèle de fermes écoles afin d’accompagner davantage de jeunes vers une agriculture moderne, résiliente et créatrice d’emplois durables.',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'rejeppat-intensifie-actions-protection-environnement',
        'title' => 'Le REJEPPAT intensifie ses actions pour la protection de l’environnement',
        'date' => '2025-06-05',
        'categories' => [
            'evenements',
        ],
        'image' => 'rejeppat-intensifie-actions-protection-environnement',
        'content' => [
            'Dans le cadre de la lutte contre les effets des changements climatiques, le REJEPPAT multiplie les initiatives de reboisement et de restauration des terres dégradées dans plusieurs communautés rurales du Togo.',
            'À travers ses campagnes environnementales, le réseau sensibilise les producteurs agricoles à l’importance de la préservation des ressources naturelles et à l’utilisation de pratiques agricoles durables.',
            'Plus de 10 000 plants forestiers ont déjà été distribués aux communautés rurales afin de contribuer à la restauration des paysages forestiers et à la protection des écosystèmes agricoles.',
            'Le REJEPPAT encourage également l’introduction d’arbres fertilitaires dans les exploitations agricoles afin d’améliorer durablement la fertilité des sols et renforcer la résilience des producteurs face aux aléas climatiques.',
            'Ces actions traduisent l’engagement du réseau en faveur d’une agriculture durable conciliant production agricole, sécurité alimentaire et protection de l’environnement',
        ],
        'tags' => [],
        'gallery' => [],
    ],
    [
        'slug' => 'rejeppat-renforce-entrepreneuriat-agricole-jeunes',
        'title' => 'Le REJEPPAT renforce l’entrepreneuriat agricole des jeunes au Togo',
        'date' => '2025-06-05',
        'categories' => [
            'actualites',
        ],
        'image' => 'rejeppat-renforce-entrepreneuriat-agricole-jeunes',
        'content' => [
            'Le REJEPPAT continue d’accompagner les jeunes producteurs agricoles à travers des programmes de formation professionnelle et de coaching entrepreneurial.',
            'Ces initiatives visent à offrir aux jeunes ruraux les compétences nécessaires pour créer et gérer efficacement leurs propres exploitations agricoles.',
            'Les bénéficiaires sont formés sur plusieurs thématiques, notamment la gestion des exploitations agricoles, les techniques agroécologiques, la transformation des produits agricoles et l’élaboration de plans d’affaires.',
            'Le réseau met également un accent particulier sur l’autonomisation des jeunes femmes rurales afin de favoriser leur inclusion dans les chaînes de valeur agricoles.',
            'Grâce à cet accompagnement, plusieurs jeunes entrepreneurs agricoles ont réussi à développer des activités génératrices de revenus et participent aujourd’hui activement au développement économique de leurs communautés.',
        ],
        'tags' => [],
        'gallery' => [],
    ],
];
